import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  movies: [
    {
      id: 1,
      title: 'Interstellar',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 2,
      title: 'Joker',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 3,
      title: 'Oppenheimer',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 4,
      title: 'The Matrix',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
    {
      id: 5,
      title: 'Inception',
      year: 2010,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 148,
      description: "A thief enters people's dreams to steal secrets.",
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbY-KG6to1c6TnWtwLvFbPva_pqcffh7UlWiOCjmUFuA&s=10',
      trailer: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
      studioId: 1,
      directorId: 1,
      actorIds: [9, 10],
    },
    {
      id: 6,
      title: 'Interstellar',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 7,
      title: 'Joker',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 8,
      title: 'Oppenheimer',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 9,
      title: 'The Matrix',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
    //
    {
      id: 1,
      title: 'InterstellarQWEQWE',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 2,
      title: 'JokerQWEQWE',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 3,
      title: 'OppenheimerQWEQWE',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 4,
      title: 'The MatrixQWEQWE',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
    {
      id: 5,
      title: 'InceptionQWEQWE',
      year: 2010,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 148,
      description: "A thief enters people's dreams to steal secrets.",
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbY-KG6to1c6TnWtwLvFbPva_pqcffh7UlWiOCjmUFuA&s=10',
      trailer: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
      studioId: 1,
      directorId: 1,
      actorIds: [9, 10],
    },
    {
      id: 6,
      title: 'Interstellar',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 7,
      title: 'Joker',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 8,
      title: 'Oppenheimer',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 9,
      title: 'The Matrix',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
    //
    {
      id: 1,
      title: 'Interstellar',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 2,
      title: 'Joker',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 3,
      title: 'Oppenheimer',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 4,
      title: 'The Matrix',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
    {
      id: 5,
      title: 'Inception',
      year: 2010,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 148,
      description: "A thief enters people's dreams to steal secrets.",
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbY-KG6to1c6TnWtwLvFbPva_pqcffh7UlWiOCjmUFuA&s=10',
      trailer: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
      studioId: 1,
      directorId: 1,
      actorIds: [9, 10],
    },
    {
      id: 6,
      title: 'Interstellar',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 7,
      title: 'Joker',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 8,
      title: 'Oppenheimer',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 9,
      title: 'The Matrix',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
    //
    {
      id: 1,
      title: 'Interstellar',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 2,
      title: 'Joker',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 3,
      title: 'Oppenheimer',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 4,
      title: 'The Matrix',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
    {
      id: 5,
      title: 'Inception',
      year: 2010,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 148,
      description: "A thief enters people's dreams to steal secrets.",
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbY-KG6to1c6TnWtwLvFbPva_pqcffh7UlWiOCjmUFuA&s=10',
      trailer: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
      studioId: 1,
      directorId: 1,
      actorIds: [9, 10],
    },
    {
      id: 6,
      title: 'Interstellar',
      year: 2014,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 169,
      description:
        'A team of astronauts travels through a wormhole in search of a new home for humanity.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN6MBU9VxzNxqU0gzzOsgDR0Mpxn4_6BDHIzD-Xc8YaQ&s=10',
      trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
      studioId: 1,
      directorId: 1,
      actorIds: [1, 2, 3],
    },
    {
      id: 7,
      title: 'Joker',
      year: 2019,
      genre: 'Drama',
      country: 'USA',
      duration: 122,
      description:
        'Arthur Fleck slowly descends into madness and becomes the Joker.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPOXFFZpg7J8ka6L6mvKWbczd0RSi6cewOp5cssjDsAg&s',
      trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
      studioId: 2,
      directorId: 2,
      actorIds: [4],
    },
    {
      id: 8,
      title: 'Oppenheimer',
      year: 2023,
      genre: 'Biography',
      country: 'USA',
      duration: 180,
      description:
        'The story of physicist J. Robert Oppenheimer and the Manhattan Project.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gsJAEwsM9Y3lIK2f6M24jtsae8ljoF2kFvC03Qn7Tw&s',
      trailer: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
      studioId: 3,
      directorId: 1,
      actorIds: [5, 6],
    },
    {
      id: 9,
      title: 'The Matrix',
      year: 1999,
      genre: 'Science Fiction',
      country: 'USA',
      duration: 136,
      description: 'A hacker discovers that reality is a computer simulation.',
      poster:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiSWTPdu0wOgC67hH3Ftm4o7Ckgm9OH1xWHbBb1zLCw&s=10',
      trailer: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
      studioId: 4,
      directorId: 3,
      actorIds: [7, 8],
    },
  ],
};

const moviesSlice = createSlice({
  initialState,
  name: 'movies',
  reducers: {
    addMovie: (state, action) => {},
  },
});

const { reducer, actions } = moviesSlice;

export default reducer;
